spring:
  profiles:
    active: local

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss+09:00"
    time-zone: Asia/Seoul

  output:
    ansi:
      enabled: always

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  batch:
    chunk-size: 100

logging:
  config: classpath:logback-spring.xml
  file:
    name: asp-api
---
spring:
  config:
    activate:
      on-profile: local

  batch:
    job:
      enabled: true
    jdbc:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=BIXACCDT_BIXOLON;sendStringParametersAsUnicode=false;encrypt=true;trustServerCertificate=true;
      username: asp_account
      password: bixolon1!@
      validationQuery: select 1
      initialize-schema: embedded
    schema:
      script: classpath:/org/springframework/batch/core/schema-sqlserver.sql

  application:
    aspdb: BIXASP_BIXOLON
    smsdb: BIXSMS_BIXOLON

  pg-billing:
    mid: wpaybill01
    signKey: b3VGY2R5ZzI5M2xCZzhrT0paQ1oxQT09
    apiIv: 1111111111111111
    apiKey: 11111111111111111111111111111111
    issuedBillKeyUrl: https://tpayapi.paywelcome.co.kr/billing/billkey/card
    billingUrl: https://tpayapi.paywelcome.co.kr/noauth/billkey/card
    deleteBillKeyUrl: https://tpayapi.paywelcome.co.kr/billing/billkey/delete
    partialCancelUrl: https://tpayapi.paywelcome.co.kr/cancel/repay
    allCancelUrl: https://tpayapi.paywelcome.co.kr/cancel/cancel
  datasource:
    master:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=BIXACCDT_BIXOLON;sendStringParametersAsUnicode=false
      username: asp_account
      password: bixolon1!@
      initial-size: 1
      max-total: 10
      max-idle: 3
      min-idle: 3
      max-wait-millis: 3000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query-timeout: 10000
      default-auto-commit: true
      pool-prepared-statements: true
      max-open-prepared-statements: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: "mhheo.dev@gmail.com"
    password: "mdvrroitxzjzhuxy"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  file:
    path: E:\project\bixolon_pos\backendlog